# Makefile — cloud-only PopolaLoom shortcuts.
# Generated by `popola init --target=cloud-only` (v0.9.0+).
#
# These targets wrap `popola dispatch --cli=cursor-cloud` flows so a
# fresh operator can smoke-test cloud dispatch without memorising every
# flag. Override variables on the command line, e.g.:
#
#   make dispatch PROMPT="Plan database migration scaffolding"
#   make status   TASK_ID=cursor-cloud-deadbeef
#   make relay    TASK_ID=cursor-cloud-deadbeef

PROMPT  ?= Describe the cloud task here
CWD     ?= .
TASK_ID ?=

.PHONY: help dispatch status attach relay

help: ## Show this help.
	@echo "PopolaLoom cloud-only Makefile (v0.9.0+):"
	@echo "  make dispatch PROMPT=\"...\"   — popola dispatch --cli=cursor-cloud"
	@echo "  make status   TASK_ID=...      — popola status <id>"
	@echo "  make attach   TASK_ID=...      — popola attach <id> --follow"
	@echo "  make relay    TASK_ID=...      — popola relay <id>"

dispatch: ## Dispatch a new cloud task via cursor-cloud.
	popola dispatch "$(PROMPT)" --cli=cursor-cloud --cwd "$(CWD)"

status: ## Show task status.
	@if [ -z "$(TASK_ID)" ]; then echo "error: TASK_ID is required" >&2; exit 2; fi
	popola status "$(TASK_ID)"

attach: ## Tail task events (SSE-by-default for cloud tasks).
	@if [ -z "$(TASK_ID)" ]; then echo "error: TASK_ID is required" >&2; exit 2; fi
	popola attach "$(TASK_ID)" --follow

relay: ## Relay a completed cloud task into a new run.
	@if [ -z "$(TASK_ID)" ]; then echo "error: TASK_ID is required" >&2; exit 2; fi
	popola relay "$(TASK_ID)"
